package com.redhat.demos.four_eyes_principle;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Applicant implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Name")
   private java.lang.String name;
   @org.kie.api.definition.type.Label(value = "Surname")
   private java.lang.String surName;
   @org.kie.api.definition.type.Label(value = "Social Security Number")
   private java.lang.String ssn;

   public Applicant()
   {
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public java.lang.String getSurName()
   {
      return this.surName;
   }

   public void setSurName(java.lang.String surName)
   {
      this.surName = surName;
   }

   public java.lang.String getSsn()
   {
      return this.ssn;
   }

   public void setSsn(java.lang.String ssn)
   {
      this.ssn = ssn;
   }

   public Applicant(java.lang.String name, java.lang.String surName,
         java.lang.String ssn)
   {
      this.name = name;
      this.surName = surName;
      this.ssn = ssn;
   }

}