package com.redhat.demos.four_eyes_principle;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Description("Marker fact to identify that this application requires 4 eyes for approval.")
public class FourEyesRequired implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   public FourEyesRequired()
   {
   }

}