package com.redhat.demos.four_eyes_principle;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class LoanApplication implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("Application ID")
   private java.lang.String applicationId;
   @org.kie.api.definition.type.Label("Applicant")
   private com.redhat.demos.four_eyes_principle.Applicant applicant;
   @org.kie.api.definition.type.Label("Amount")
   private java.math.BigDecimal amount;

   public LoanApplication()
   {
   }

   public java.lang.String getApplicationId()
   {
      return this.applicationId;
   }

   public void setApplicationId(java.lang.String applicationId)
   {
      this.applicationId = applicationId;
   }

   public com.redhat.demos.four_eyes_principle.Applicant getApplicant()
   {
      return this.applicant;
   }

   public void setApplicant(
         com.redhat.demos.four_eyes_principle.Applicant applicant)
   {
      this.applicant = applicant;
   }

   public java.math.BigDecimal getAmount()
   {
      return this.amount;
   }

   public void setAmount(java.math.BigDecimal amount)
   {
      this.amount = amount;
   }

   public LoanApplication(
         com.redhat.demos.four_eyes_principle.Applicant applicant,
         java.math.BigDecimal amount, java.lang.String applicationId)
   {
      this.applicant = applicant;
      this.amount = amount;
      this.applicationId = applicationId;
   }

   public LoanApplication(java.lang.String applicationId,
         com.redhat.demos.four_eyes_principle.Applicant applicant,
         java.math.BigDecimal amount)
   {
      this.applicationId = applicationId;
      this.applicant = applicant;
      this.amount = amount;
   }

}